apiVersion: apps/v1
kind: Deployment #Deployment in kubernetes is a collection of POD's
metadata:
  name: nginx-deployment
spec:
  replicas: 8 # original name
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # common name
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
